# Generated by Django 6.0.1 on 2026-01-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_weather_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_codes',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
