# Generated by Django 6.0.1 on 2026-01-29 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_weather_codes_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weathercode2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weatherapp.weather_codes'),
        ),
    ]
