# Generated by Django 6.0.1 on 2026-01-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_weather_weathercode2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_codes',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
