# Generated by Django 6.0.1 on 2026-01-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0005_alter_weather_codes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weathercode2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weatherapp.weather_codes', to_field='code'),
        ),
    ]
