# Generated by Django 6.0.1 on 2026-01-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TG_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID пользователя Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя в Telegram')),
                ('telegram_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('telegram_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='telegram_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapp.tg_author'),
        ),
    ]
