# Generated by Django 6.0.1 on 2026-01-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_tg_author_news_telegram_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tg_author',
            name='telegram_first_name',
        ),
        migrations.RemoveField(
            model_name='tg_author',
            name='telegram_last_name',
        ),
        migrations.AlterField(
            model_name='tg_author',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tg_author',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tg_author',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
