# Generated by Django 6.0.1 on 2026-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_news_image_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=10),
        ),
    ]
