# Generated by Django 6.0.1 on 2026-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_news_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
