# Generated by Django 6.0.1 on 2026-02-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_remove_news_is_approved_news_moderated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_updated',
        ),
    ]
