# Generated by Django 6.0.1 on 2026-02-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_remove_news_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tg_author',
            name='date_created',
        ),
    ]
