# Generated by Django 6.0.1 on 2026-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_remove_news_status_news_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
