# Generated by Django 6.0.1 on 2026-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_remove_tg_author_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tg_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
