# Generated by Django 6.0.1 on 2026-02-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_news_tg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tg_image',
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
