# Generated by Django 6.0.1 on 2026-01-18 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_news_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
